### ISSUE TITLE
Release pretrained models on Shapenet dataset

### ISSUE THREAD

**Issue by ItsThanhTung** [szymanowiczs/viewset-diffusion#2]
I'm experimenting with the Viewset diffusion. It would be great if we can evaluate the model using pretrained weights. Please release them. Thanks!

**Comment by szymanowiczs** [comment]
Hi @ItsThanhTung ! Apologies for the delay. I am still figuring out how to best host them, but for the purpose of time, I uploaded the checkpoint for ShapeNet cars which you can use now. Find it here: https://drive.google.com/drive/folders/1837UhwVTFNbozUI7RKFdVpFOjTETVvMz?usp=sharing

I'll try to upload the rest asap, but I hope releasing this one now will be useful for you!

**Comment by szymanowiczs** [comment]
All models are released :)
