### ISSUE TITLE
Missing file "random_order_of_sample_idxs" for quantitative evaluation

### ISSUE THREAD

**Issue by lukasHoel** [szymanowiczs/viewset-diffusion#5]
Hi,

I'm trying to reproduce the number with ```evaluation_quantitative.py```, but there is a missing file ```random_order_of_sample_idxs.npy```.

I generated the compressed dataset with your code, but it only produced the following files:

```
camera_Rs_test.npz
camera_Ts_train.npz
focal_lengths_test.npz
images_train.npz
principal_points_val.npz
camera_Rs_train.npz
camera_Ts_val.npz
focal_lengths_train.npz
images_val.npz
sequences_to_check_test.txt
camera_Rs_val.npz
fixed_frame_idxs_test.npy
focal_lengths_val.npz
principal_points_test.npz
sequences_to_check_train.txt
camera_Ts_test.npz
fixed_frame_idxs_val.npy
images_test.npz
principal_points_train.npz
sequences_to_check_val.txt
```

How can I create the missing file?

Thanks!

**Comment by lukasHoel** [comment]
It seems to work when setting ```with_index_selection=False``` here https://github.com/szymanowiczs/viewset-diffusion/blob/a8a74ae4712d9356b70785612cd261ec4ff2746e/evaluation_quantitative.py#L41

**Comment by szymanowiczs** [comment]
Hi @lukasHoel - apologies! I forgot to include these. They are now in the Google Drive together with models. I included instructions in Readme. You should keep with_index_selection=True to reproduce the scores (this makes sure you evaluate on the same source and target frames).

**Comment by lukasHoel** [comment]
Thanks @szymanowiczs for providing it so fast! I have another question: say I want to evaluate on a novel co3d category (e.g. donut/apple). Would it be sufficient to select the "fixed frame indices" for each object at random? This would mean that some of the frame-combinations could be pretty close together and then novel-view-synthesis is easier than for samples that are further apart. Or were you using some sort of stratified sampling when constructing these indices to avoid this?

**Comment by szymanowiczs** [comment]
I formed the testing indices at random. Ideally one should test all combinations. In fact, you want to test some samples that have views close and some that have them far away, for example to check that diffusion doesn't make reconstructions in nearby worse. Testing all combinations was too expensive because I wanted to take 100 random samples for each testing pair, so taking 100 random indices was an approximation.
