### ISSUE TITLE
Evaluate custom-trained checkpoint gives error

### ISSUE THREAD

**Issue by lukasHoel** [szymanowiczs/viewset-diffusion#6]
Hi @szymanowiczs,

I once again need your help. I now trained my own checkpoints for 300K iters using this command:

```
python train.py +experiment=diffusion_128 +arch=up_3d_conv +dataset=co3d_donut
```

The following model checkpoints are stored:

```
model.pth --> 1.2 GB file
model_296000.pth --> 400 MB file
```

I tried to run an evaluation with this checkpoint, but it goes state-dict error:

```
python evaluation_qualitative.py [model_path] --dataset_name [dataset_name] --N_clean 0 --N_noisy 4 --cf_guidance -1.0 --seed 0
```

This is the error:

```
RuntimeError: Error(s) in loading state_dict for ViewsetDiffusion:
        Missing key(s) in state_dict: "model.reconstructor.conv_upsampler.1.block1.proj.weight", "model.reconstructor.conv_upsampler.1.block1.proj.bias", "model.reconstructor.conv_upsampler.1.block1.norm.weight", "model.reconstructor.conv_upsampler.1.block1.norm.bias", "model.reconstructor.conv_upsampler.1.block2.proj.weight", "model.reconstructor.conv_upsampler.1.block2.proj.bias", "model.reconstructor.conv_upsampler.1.block2.norm.weight", "model.reconstructor.conv_upsampler.1.block2.norm.bias", "model.reconstructor.conv_upsampler.2.block1.proj.weight", "model.reconstructor.conv_upsampler.2.block1.proj.bias", "model.reconstructor.conv_upsampler.2.block1.norm.weight", "model.reconstructor.conv_upsampler.2.block1.norm.bias", "model.reconstructor.conv_upsampler.2.block2.proj.weight", "model.reconstructor.conv_upsampler.2.block2.proj.bias", "model.reconstructor.conv_upsampler.2.block2.norm.weight", "model.reconstructor.conv_upsampler.2.block2.norm.bias".
```

I notice that the pretrained checkpoints are rather around 400 MB, but also the ```model_296000.pth``` did not work. Also, I had to copy the ```.hydra``` directory from another checkpoint because it was not created for me. 

I guess I am missing some step to convert the saved ```model.pth``` into something that can be executed with the test scripts?

**Comment by lukasHoel** [comment]
The model loads successfully when changing ```render.volume_size=32``` in the ```.hydra/config.yaml```. But not sure if this is the correct fix. I notice that in the ```configs/arch/up_3d_conv.yaml```, the ```render.volume_size=64```, but the ```model.volume_size=32```.

**Comment by szymanowiczs** [comment]
Hi @lukasHoel - from what you're saying it seems the model trains without the 3D conv upsampler. After a bit of digging I found out this is an issue in the instructions / configs I shared. In co3d_donut.yaml can you set render.volume_size=64 and check that this evaluates to true https://github.com/szymanowiczs/viewset-diffusion/blob/45003948f2ea6b70f72e5dc60b14beb2428699a4/model/multi_image_unet.py#L122 ?

I.e. that the upsampler is being created?
You want render.volume_size=64 and model.volume_size=32. You want a 64x64x64 volume at the end for best resolution but most of the processing in the U-Net to be at 32x32x32 or lower for efficiency.

**Comment by lukasHoel** [comment]
Thanks for the explanation, I'll try it out!
